name: Deploy to Firebase Hosting on Merge

on:
  push:
    branches:
      - master  # Change this to your default branch name if necessary

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'  # Specify the Node.js version you need

    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    - name: Add new site to firebase.json
      run: |
        # Detect new folder (e.g., kirai1)
        NEW_SITE=$(ls public | grep kirai) # Example: kirai1
        # Update firebase.json to include the new site
        echo "Updating firebase.json with new site: $NEW_SITE"
        jq --arg site "$NEW_SITE" '.hosting += [{"target": $site, "public": ("public/" + $site), "ignore": ["firebase.json", "/.", "/node_modules/*"]}]' firebase.json > temp.json && mv temp.json firebase.json
        git add firebase.json
        git commit -m "Added new site $NEW_SITE to firebase.json"
        git push

    - name: Deploy to Firebase Hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      run: firebase deploy --only hosting
